from flask import Blueprint, render_template
from app.model.category import Category
from app.model.product import Product

home_bp = Blueprint('home', __name__)

categories = [Category(1, "Eletrônicos"), Category(2, "Livros"), Category(3, "Outros")]
products = [
    Product(1, "EduCat AI", "Estudantes enfrentam dificuldades com métodos de aprendizado tradicionais, que muitas vezes não atendem às suas necessidades e estilos individuais.", "Uma plataforma de aprendizado personalizada que adapta o conteúdo e o ritmo de estudo para cada aluno, maximizando a retenção de conhecimento.", "contact@educatai.com", "No mundo atual, os métodos tradicionais de ensino frequentemente falham em atender às necessidades únicas de cada aluno. Com o EduCat AI, estamos revolucionando o aprendizado ao oferecer uma plataforma personalizada que adapta o conteúdo e o ritmo de estudo para cada estudante. Ao combinar inteligência artificial com metodologias pedagógicas avançadas, garantimos que cada aluno receba a atenção e os recursos necessários para maximizar sua retenção e sucesso acadêmico. EduCat AI não é apenas uma plataforma de aprendizado; é o futuro da educação personalizada."
    ),
    Product(2, "MindGuide", "Acesso limitado a suporte de saúde mental, especialmente em momentos de necessidade urgente, e estigmatização da busca por ajuda profissional.", "Um assistente virtual que oferece suporte emocional instantâneo e discreto, utilizando técnicas de terapia para ajudar na gestão de saúde mental", "support@mindguide.com", "A saúde mental é fundamental, mas muitos enfrentam dificuldades para encontrar suporte quando mais precisam. O MindGuide é um assistente virtual que oferece suporte emocional instantâneo e discreto, utilizando técnicas de terapia comprovadas para ajudar na gestão da saúde mental. Disponível 24/7, o MindGuide quebra o estigma e oferece um espaço seguro e acessível para todos que precisam de ajuda. Com o MindGuide, o apoio emocional está sempre ao seu alcance, quando você mais precisa.",
    ),
    Product(3, "EcoWardrobe", "A indústria da moda rápida contribui significativamente para o desperdício e a poluição ambiental, com roupas sendo descartadas rapidamente.", "Uma plataforma que permite o aluguel de roupas de alta qualidade, promovendo a reutilização e a sustentabilidade na moda.", "info@ecowardrobe.com", "A indústria da moda rápida está destruindo o meio ambiente com desperdício e poluição. O EcoWardrobe é a solução sustentável que você estava esperando. Nossa plataforma oferece aluguel de roupas de alta qualidade, permitindo que você desfrute das últimas tendências sem contribuir para o problema do desperdício. Ao promover a reutilização e a sustentabilidade, o EcoWardrobe transforma a maneira como você se veste, ajudando o planeta enquanto você fica na moda."
    ),
    Product(4, "LocalHarvest Hub", "Consumidores têm dificuldade em acessar alimentos frescos e locais, enquanto pequenos produtores lutam para alcançar mercados maiores.", "Um marketplace que conecta produtores locais com consumidores, facilitando o acesso a alimentos frescos e fortalecendo a economia local.", "hello@localharvesthub.com","Você quer acessar alimentos frescos e locais, mas muitas vezes enfrenta barreiras para encontrar o que precisa. O LocalHarvest Hub conecta diretamente pequenos produtores locais com consumidores que valorizam alimentos frescos e de qualidade. Nosso marketplace facilita a compra e venda de produtos locais, fortalecendo a economia regional e garantindo que você tenha acesso ao melhor que sua comunidade tem a oferecer. Com o LocalHarvest Hub, apoiar produtores locais e comer bem nunca foi tão fácil." 
    ),
    Product(5, "CollabFlow", "Equipes distribuídas enfrentam desafios na comunicação e no gerenciamento de projetos, resultando em baixa produtividade e falhas na execução.", "Uma plataforma de gerenciamento de projetos colaborativos que integra ferramentas de comunicação e organização para melhorar a eficiência da equipe.", "team@collabflow.com", "Equipes distribuídas enfrentam desafios constantes de comunicação e gerenciamento, resultando em baixa produtividade e falhas na execução. O CollabFlow é a solução definitiva para esses problemas. Nossa plataforma integra ferramentas de comunicação e organização em um único lugar, melhorando a eficiência da equipe e garantindo uma colaboração eficaz. Com o CollabFlow, seus projetos serão mais bem geridos e suas equipes mais produtivas, não importa onde estejam."
    ),
    Product(6, "SunEco Solutions", "Muitos lares não conseguem acessar soluções de energia renovável devido a custos iniciais elevados e complexidade na instalação.", "Fornecer sistemas acessíveis e fáceis de instalar para geração e armazenamento de energia renovável, ajudando a reduzir custos e emissões de carbono.","connect@suneco.com", "A transição para a energia renovável pode ser cara e complexa, mas não precisa ser assim. O SunEco Solutions oferece sistemas de energia renovável acessíveis e fáceis de instalar para residências, reduzindo custos e emissões de carbono. Nossos produtos tornam a geração e armazenamento de energia solar uma realidade simples e econômica, ajudando você a fazer a diferença no meio ambiente sem complicações. Com o SunEco Solutions, o futuro sustentável começa em sua casa."
    )
]

@home_bp.route('/')
def home():
    return render_template('index.html', categories=categories, products=Product.all_products)
